#!/bin/bash
###############################################################################
# fix-hdmi-edid.sh
#
# Captures the current HDMI EDID and configures the NVIDIA driver to use
# the cached copy instead of polling the monitor. Prevents compositor
# freezes caused by intermittent EDID read failures.
#
# Run with: sudo ./scripts/fix-hdmi-edid.sh
#
# Prerequisites: working HDMI connection (the monitor must be displaying
# correctly when you run this, so we capture a valid EDID).
###############################################################################

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[NOTE]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1"; }

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run with sudo:"
    echo "  sudo $0"
    exit 1
fi

echo "============================================================"
echo " HDMI EDID Static Override"
echo " Prevents compositor freeze from EDID read failures"
echo "============================================================"
echo ""

# ── Find the HDMI connector ─────────────────────────────────────────────────

HDMI_EDID=""
HDMI_CARD=""

for edid_path in /sys/class/drm/card*-HDMI-A-*/edid; do
    if [ -f "$edid_path" ] && [ -s "$edid_path" ]; then
        HDMI_EDID="$edid_path"
        HDMI_CARD=$(echo "$edid_path" | grep -oP 'card\d+-HDMI-A-\d+')
        break
    fi
done

if [ -z "$HDMI_EDID" ]; then
    err "No active HDMI connection found."
    echo ""
    echo "Available connectors:"
    for d in /sys/class/drm/card*-*/; do
        name=$(basename "$d")
        status=$(cat "$d/status" 2>/dev/null || echo "unknown")
        printf "  %-30s %s\n" "$name" "$status"
    done
    echo ""
    echo "Make sure the monitor is connected and displaying via HDMI,"
    echo "then re-run this script."
    exit 1
fi

log "Found active HDMI: $HDMI_CARD"
echo "  EDID source: $HDMI_EDID"

# ── Read monitor info from EDID ─────────────────────────────────────────────

MONITOR_NAME=""
if command -v edid-decode &>/dev/null; then
    MONITOR_NAME=$(cat "$HDMI_EDID" | edid-decode 2>/dev/null | grep -oP "Display Product Name: '\K[^']+" || true)
fi
if [ -z "$MONITOR_NAME" ]; then
    MONITOR_NAME=$(cat "$HDMI_EDID" | strings | head -5 | grep -i '[a-z]' | head -1 || echo "unknown")
fi
log "Monitor: $MONITOR_NAME"

# ── Capture EDID ────────────────────────────────────────────────────────────

EDID_DIR="/etc/nvidia"
EDID_FILE="$EDID_DIR/hdmi-edid.bin"

mkdir -p "$EDID_DIR"
cp "$HDMI_EDID" "$EDID_FILE"
chmod 644 "$EDID_FILE"

EDID_SIZE=$(stat -c%s "$EDID_FILE")
log "EDID captured: $EDID_FILE ($EDID_SIZE bytes)"

if [ "$EDID_SIZE" -lt 128 ]; then
    err "EDID is suspiciously small ($EDID_SIZE bytes). The monitor may not"
    err "be fully initialized. Wait for the display to stabilize and retry."
    exit 1
fi

# ── Determine the NVIDIA display name ───────────────────────────────────────

NVIDIA_DISPLAY="HDMI-0"
if command -v nvidia-smi &>/dev/null; then
    DETECTED=$(nvidia-smi --query-gpu=display_active --format=csv,noheader 2>/dev/null | head -1 || true)
    if echo "$DETECTED" | grep -qi "HDMI"; then
        log "NVIDIA confirms HDMI active"
    fi
fi

# ── Create xorg.conf.d snippet ──────────────────────────────────────────────

XORG_DIR="/etc/X11/xorg.conf.d"
XORG_CONF="$XORG_DIR/15-hdmi-edid.conf"

mkdir -p "$XORG_DIR"

cat > "$XORG_CONF" << EOF
# Force static EDID for HDMI to prevent compositor freezes from
# intermittent EDID read failures. Generated by fix-hdmi-edid.sh.
# Monitor: $MONITOR_NAME
# Date: $(date +%Y-%m-%d)

Section "Screen"
    Identifier "Default Screen"
    Option "CustomEDID" "$NVIDIA_DISPLAY:$EDID_FILE"
EndSection

Section "Device"
    Identifier "Default Device"
    Driver "nvidia"
    Option "CustomEDID" "$NVIDIA_DISPLAY:$EDID_FILE"
EndSection
EOF

log "Xorg config written: $XORG_CONF"

# ── Summary ─────────────────────────────────────────────────────────────────

echo ""
echo "============================================================"
echo -e " ${GREEN}EDID override configured${NC}"
echo ""
echo " Files created:"
echo "   $EDID_FILE"
echo "   $XORG_CONF"
echo ""
echo " The NVIDIA driver will now use the cached EDID instead of"
echo " polling the monitor. This prevents the intermittent read"
echo " failures that wedge the compositor."
echo ""
echo " REBOOT or restart X to apply:"
echo "   sudo systemctl restart display-manager"
echo ""
echo " To revert:"
echo "   sudo rm $XORG_CONF"
echo "   sudo reboot"
echo "============================================================"
